
import React, { useState, useEffect } from 'react';
import { SERVICES, CONTACT_INFO } from '../constants';
import { BookingData } from '../types';
import { generateBookingPDF } from '../services/pdfService';

interface Props {
  selectedService: string;
  onClose: () => void;
  onComplete?: (status: string) => void;
}

export const BookingModal: React.FC<Props> = ({ selectedService, onClose, onComplete }) => {
  // Generate a unique reference once when the modal opens
  const generateRef = () => {
    const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '');
    const randomStr = Math.random().toString(36).substring(2, 6).toUpperCase();
    return `GMA-${dateStr}-${randomStr}`;
  };

  const [formData, setFormData] = useState<BookingData>({
    reference: generateRef(),
    name: '',
    email: '',
    phone: '',
    service: selectedService || SERVICES[0].title,
    date: new Date().toISOString().split('T')[0],
    passengers: 1,
    notes: ''
  });

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleWhatsAppBooking = (isReceipt = false) => {
    const message = `*🌟 NEW BOOKING VOUCHER 🌟*%0A` +
      `*Reference:* ${formData.reference}%0A` +
      `--------------------------------%0A` +
      `*Name:* ${formData.name}%0A` +
      `*Service:* ${formData.service}%0A` +
      `*Date:* ${formData.date}%0A` +
      `*Passengers:* ${formData.passengers}%0A` +
      `*Contact:* ${formData.phone}%0A` +
      `*Email:* ${formData.email}%0A` +
      `*Notes:* ${formData.notes || 'No special requests'}%0A` +
      `--------------------------------%0A` +
      `${isReceipt ? '_PDF Receipt has been generated by client._' : '_Please confirm availability._'}`;
    
    window.open(`https://wa.me/${CONTACT_INFO.whatsapp}?text=${message}`, '_blank');
  };

  const handleDownloadPDF = async () => {
    if (!formData.name || !formData.email || !formData.phone) {
      alert("Please fill in your Name, Email, and Phone Number first.");
      return;
    }
    // 1. Generate PDF for client
    await generateBookingPDF(formData);
    // 2. Notify business via WhatsApp
    handleWhatsAppBooking(true);
    // 3. Show success UI
    setIsSuccess(true);
    if (onComplete) onComplete('Receipt & Booking Sent');
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setTimeout(() => {
      setIsSubmitting(false);
      handleWhatsAppBooking(false);
      setIsSuccess(true);
      if (onComplete) onComplete('Booking Request Sent');
    }, 1200);
  };

  const NEXT_STEPS = [
    {
      icon: 'fa-envelope-open-text',
      title: 'Request Received',
      desc: 'Your details and reference are now with our dispatch team for priority handling.'
    },
    {
      icon: 'fa-calendar-check',
      title: 'Availability Check',
      desc: 'We are verifying vehicle and guide availability for your specific travel dates.'
    },
    {
      icon: 'fa-headset',
      title: 'Agent Contact',
      desc: 'Our team will reach out via WhatsApp/Phone within 24 hours to confirm and finalize payment.'
    },
    {
      icon: 'fa-route',
      title: 'Safari Ready',
      desc: 'Once confirmed, your professional driver will be assigned and your journey begins!'
    }
  ];

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center px-4">
      <div className="absolute inset-0 bg-secondary/80 backdrop-blur-sm" onClick={onClose} />
      
      <div className="relative w-full max-w-2xl bg-white rounded-2xl overflow-hidden shadow-2xl transform transition-all animate-in fade-in zoom-in duration-300">
        <div className="bg-primary p-6 text-secondary flex justify-between items-center">
          <div>
            <h2 className="text-2xl font-serif font-bold uppercase tracking-tight">
              {isSuccess ? 'Booking Initiated!' : 'Secure Your Experience'}
            </h2>
            <p className="text-secondary/80 text-sm font-semibold">
              {isSuccess ? `Voucher ID: ${formData.reference}` : 'Fill in the details to book your service'}
            </p>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-secondary hover:text-primary rounded-full transition-colors">
            <i className="fa-solid fa-xmark text-xl"></i>
          </button>
        </div>

        {isSuccess ? (
          <div className="p-8 space-y-8 max-h-[85vh] overflow-y-auto">
            {/* Header Success Section */}
            <div className="text-center space-y-4">
              <div className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto text-green-600 animate-bounce-slow">
                <i className="fa-solid fa-check-double text-4xl"></i>
              </div>
              <h3 className="text-3xl font-serif font-black text-secondary italic">Asante Sana, {formData.name.split(' ')[0]}!</h3>
              <p className="text-gray-500 font-medium">Your request for <span className="text-secondary font-bold">{formData.service}</span> is being processed.</p>
            </div>

            {/* Next Steps Guide */}
            <div className="bg-gray-50 rounded-3xl p-8 border border-gray-100">
              <h4 className="text-xs font-black uppercase tracking-[0.3em] text-primary mb-8 text-center">What Happens Next</h4>
              <div className="space-y-8 relative">
                {/* Connecting Line */}
                <div className="absolute left-6 top-2 bottom-2 w-0.5 bg-primary/20" />
                
                {NEXT_STEPS.map((step, idx) => (
                  <div key={idx} className="flex gap-6 relative z-10 group">
                    <div className="w-12 h-12 rounded-2xl bg-white border border-gray-100 shadow-sm flex items-center justify-center text-primary group-hover:bg-primary group-hover:text-secondary transition-all shrink-0">
                      <i className={`fa-solid ${step.icon} text-lg`}></i>
                    </div>
                    <div>
                      <h5 className="font-bold text-secondary text-base">{step.title}</h5>
                      <p className="text-gray-500 text-sm leading-relaxed">{step.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            
            {/* Important Tip */}
            <div className="bg-primary/10 border-2 border-dashed border-primary p-6 rounded-2xl text-center">
              <p className="text-secondary font-bold text-sm uppercase tracking-widest mb-2">💡 One Final Step</p>
              <p className="text-secondary/70 text-sm">
                If you downloaded a PDF, please **attach it to the WhatsApp chat** now. This ensures our team can verify your reference instantly!
              </p>
            </div>

            <button 
              onClick={onClose}
              className="w-full py-5 bg-secondary text-primary font-black rounded-xl hover:bg-primary hover:text-secondary transition-all shadow-lg active:scale-95 text-lg"
            >
              GOT IT, CLOSE
            </button>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="p-8 space-y-6 max-h-[75vh] overflow-y-auto">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <label className="text-sm font-semibold text-secondary">Full Name</label>
                <input
                  required
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  placeholder="John Doe"
                  className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-semibold text-secondary">Email Address</label>
                <input
                  type="email"
                  required
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  placeholder="john@example.com"
                  className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-semibold text-secondary">Phone Number</label>
                <input
                  required
                  name="phone"
                  value={formData.phone}
                  onChange={handleChange}
                  placeholder="07XX XXX XXX"
                  className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-semibold text-secondary">Service Type</label>
                <select
                  name="service"
                  value={formData.service}
                  onChange={handleChange}
                  className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                >
                  {SERVICES.map(s => <option key={s.id} value={s.title}>{s.title}</option>)}
                </select>
              </div>
              <div className="space-y-2">
                <label className="text-sm font-semibold text-secondary">Preferred Date</label>
                <input
                  type="date"
                  required
                  name="date"
                  value={formData.date}
                  onChange={handleChange}
                  className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-semibold text-secondary">Number of Passengers</label>
                <input
                  type="number"
                  min="1"
                  max="50"
                  name="passengers"
                  value={formData.passengers}
                  onChange={handleChange}
                  className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all"
                />
              </div>
            </div>

            <div className="space-y-2">
              <label className="text-sm font-semibold text-secondary">Additional Information / Requests</label>
              <textarea
                name="notes"
                value={formData.notes}
                onChange={handleChange}
                rows={3}
                placeholder="Tell us about special requirements or your destination..."
                className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all resize-none"
              />
            </div>

            <div className="flex flex-col sm:flex-row gap-4 pt-4 border-t border-gray-100">
              <button
                type="button"
                onClick={handleDownloadPDF}
                className="flex-1 flex items-center justify-center gap-2 px-6 py-4 border-2 border-primary text-secondary font-bold rounded-xl hover:bg-primary hover:text-secondary transition-all"
              >
                <i className="fa-solid fa-file-pdf"></i>
                GET PDF RECEIPT
              </button>
              <button
                type="submit"
                disabled={isSubmitting}
                className="flex-[2] flex items-center justify-center gap-2 px-6 py-4 bg-primary text-secondary font-black rounded-xl hover:bg-secondary hover:text-primary hover:scale-[1.02] active:scale-95 transition-all disabled:opacity-50 shadow-lg"
              >
                {isSubmitting ? (
                  <i className="fa-solid fa-circle-notch animate-spin"></i>
                ) : (
                  <>
                    <i className="fa-brands fa-whatsapp text-xl"></i>
                    BOOK VIA WHATSAPP
                  </>
                )}
              </button>
            </div>
            <p className="text-center text-[10px] text-gray-400 uppercase font-black tracking-widest">
              Booking Ref: {formData.reference}
            </p>
          </form>
        )}
      </div>
    </div>
  );
};
